services:
  flutter:
    build: .
    volumes:
      - .:/app
      - flutter_pub_cache:/root/.pub-cache
      - gradle_cache:/root/.gradle
      - android_ndk:/opt/android-sdk/ndk
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  flutter_pub_cache:
  gradle_cache:
  android_ndk:
